// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostRoute.DAL;

#nullable disable

namespace PostRoute.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526133832_AddIssueManagement")]
    partial class AddIssueManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostRoute.DAL.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActionAssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActionAssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionAssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AssignedAction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionAssignedByUserId");

                    b.HasIndex("ActionAssignedToUserId");

                    b.HasIndex("MailboxId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("RouteItemId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("IssueNotifications");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueStatusHistories");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstallationYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlwaysAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeOnly?>("Slot1End")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Slot1Start")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Slot2End")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Slot2Start")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Mailboxes");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.MailboxAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("UserId");

                    b.ToTable("MailboxAuditLogs");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("ExceedsStandardTime")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReorderedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReorderedBy")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("PlannedEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("PlannedStartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PostmanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostmanId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.RouteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EstimatedArrivalTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsManuallyReordered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProcessedStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnavailableReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteItems");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.SecurityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AttemptedUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecurityLogs");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Issue", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.User", "ActionAssignedByUser")
                        .WithMany()
                        .HasForeignKey("ActionAssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PostRoute.DAL.Entities.User", "ActionAssignedToUser")
                        .WithMany()
                        .HasForeignKey("ActionAssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PostRoute.DAL.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.RouteItem", "RouteItem")
                        .WithMany()
                        .HasForeignKey("RouteItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionAssignedByUser");

                    b.Navigation("ActionAssignedToUser");

                    b.Navigation("Mailbox");

                    b.Navigation("ReportedBy");

                    b.Navigation("RouteItem");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueComment", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueNotification", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.Issue", "Issue")
                        .WithMany("Notifications")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.IssueStatusHistory", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PostRoute.DAL.Entities.Issue", "Issue")
                        .WithMany("StatusHistory")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.MailboxAuditLog", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mailbox");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Route", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.User", "Postman")
                        .WithMany()
                        .HasForeignKey("PostmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Postman");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.RouteItem", b =>
                {
                    b.HasOne("PostRoute.DAL.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PostRoute.DAL.Entities.Route", "Route")
                        .WithMany("RouteItems")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mailbox");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Issue", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("PostRoute.DAL.Entities.Route", b =>
                {
                    b.Navigation("RouteItems");
                });
#pragma warning restore 612, 618
        }
    }
}
